CREATE OR REPLACE TABLE test.transactions (
    TRANSACTION_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
    SOURCE_ID CHAR(10) NOT NULL PRIMARY KEY,
    PAYER_NAME VARCHAR(80) NOT NULL,
    TRANSACTION_AMOUNT DECIMAL NOT NULL,
    TRANSACTION_TYPE VARCHAR(20) NOT NULL
);

CREATE INDEX idx_transaction_date ON test.transactions (TRANSACTION_DATE);
CREATE INDEX idx_payer_name ON test.transactions (PAYER_NAME);

COPY test.transactions FROM '/DIRECTORY/settlement-report-USER_ID-2025-03-01-065004.csv' DELIMITER ',' CSV HEADER;